{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: healthcare-app-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      - path: /patients
        pathType: Prefix
        backend:
          service:
            name: {{ $.Values.patientService.name }}
            port:
              number: {{ $.Values.patientService.port }}
      - path: /appointments
        pathType: Prefix
        backend:
          service:
            name: {{ $.Values.appointmentService.name }}
            port:
              number: {{ $.Values.appointmentService.port }}
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: {{ $.Values.patientService.name }}
            port:
              number: {{ $.Values.patientService.port }}
  {{- end }}
{{- end }}