apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.patientService.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.patientService.name }}
spec:
  selector:
    app: {{ .Values.patientService.name }}
  ports:
  - port: {{ .Values.patientService.port }}
    targetPort: {{ .Values.patientService.port }}
    protocol: TCP
  type: {{ .Values.patientService.serviceType }}