apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3001
