global:
  namespace: healthcare
  environment: dev
  
image:
  registry: lbsaksacr.azurecr.io
  pullPolicy: IfNotPresent
  
patientService:
  name: patient-service
  replicaCount: 2
  image: patient-service
  tag: latest
  port: 3000
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  hpa:
    minReplicas: 2
    maxReplicas: 10
    targetCPU: 50
    targetMemory: 70

appointmentService:
  name: appointment-service
  replicaCount: 2
  image: appointment-service
  tag: latest
  port: 3001
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  hpa:
    minReplicas: 2
    maxReplicas: 10
    targetCPU: 50
    targetMemory: 70

ingress:
  enabled: true
  className: "azure/application-gateway"
  annotations: {}
  hosts:
    - host: lbghealthcare.dev.example.com
      paths:
        - path: /
          pathType: Prefix